version: '3'

services:
  # app:
  #   # build: .
  #   image: ignite-repl
  #   ports:
  #     - "3333:3333"

  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"

  server_1:
    image: gridgain/community:8.8.7-openjdk11
    # image: apacheignite/ignite:2.10.0
    ports:
      - "9011:9011"
      - "47101:47101"
      - "47501:47501"
      - "10801:10800"
      - "11211:11211"
      - "5005:5005"
    volumes:
      - ./ignite:/ignite
      - ./config:/config
    environment:
      - "CONSISTENT_ID=server_1"
      - "DC=dc1"
      - "PORT=47101"

      - "IGNITE_QUIET=false"
      - "IGNITE_WORK_DIR=/ignite"
      - "CONFIG_URI=/config/server.xml"
      - "OPTION_LIBS=ignite-zookeeper"
      - >-
        JVM_OPTS=-Xms512m -Xmx512m
        -XX:+AggressiveOpts
        -XX:+UseG1GC
        -XX:MaxDirectMemorySize=256m
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.port=9011
        -Dcom.sun.management.jmxremote.rmi.port=9011
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false
        -Dcom.sun.management.jmxremote.local.only=false
        -Djava.rmi.server.hostname=127.0.0.1
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    depends_on:
      - zookeeper

  server_2:
    image: gridgain/community:8.8.7-openjdk11
    # image: apacheignite/ignite:2.10.0
    ports:
      - "9012:9012"
      - "47102:47102"
      - "47502:47502"
      - "10802:10800"
      - "11212:11211"
      - "5006:5006"
    volumes:
      - ./ignite:/ignite
      - ./config:/config
    environment:
      - "CONSISTENT_ID=server_2"
      - "DC=dc2"
      - "PORT=47102"

      - "IGNITE_QUIET=false"
      - "IGNITE_WORK_DIR=/ignite"
      - "CONFIG_URI=/config/server.xml"
      - "OPTION_LIBS=ignite-zookeeper"
      - >-
        JVM_OPTS=-Xms512m -Xmx512m
        -XX:+AggressiveOpts
        -XX:+UseG1GC
        -XX:MaxDirectMemorySize=256m
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.port=9012
        -Dcom.sun.management.jmxremote.rmi.port=9012
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false
        -Dcom.sun.management.jmxremote.local.only=false
        -Djava.rmi.server.hostname=127.0.0.1
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006
    depends_on:
      - zookeeper
